import "dotenv/config";
import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const db = new PrismaClient({ adapter });

async function main() {
  console.log("Sembrando tasas laborales globales (Comercio CCT 130/75 + IPS Formosa, GONZALEZ.xlsm)...");
  const vigenciaDesde = new Date("2026-01-01");
  const tasasGlobales: { clave: Parameters<typeof db.tasaLaboral.create>[0]["data"]["clave"]; valor: number }[] = [
    // Aportes del trabajador
    { clave: "APORTE_JUBILACION", valor: 0.11 },
    { clave: "APORTE_LEY19032_PAMI", valor: 0.03 },
    { clave: "APORTE_OBRA_SOCIAL", valor: 0.06 }, // Comercio 130/75: 6%, no 3%
    // Contribuciones patronales
    { clave: "CONTRIB_JUBILACION", valor: 0.1077 },
    { clave: "CONTRIB_LEY19032", valor: 0.0159 },
    { clave: "CONTRIB_OBRA_SOCIAL", valor: 0.06 },
    { clave: "CONTRIB_ASIG_FAMILIARES", valor: 0.047 },
    { clave: "CONTRIB_FNE", valor: 0.0094 },
    { clave: "CONTRIB_ART", valor: 0.03 }, // componente % — ver ART_FFEP_FIJO para la cuota fija
    // Deducciones sindicales/Comercio
    { clave: "CONTRIB_SINDICAL", valor: 0.04 }, // usado como % de "SINDICATO" (deducción, no contribución patronal)
    { clave: "DEDUCCION_FAECYS", valor: 0.005 },
    { clave: "DEDUCCION_IPS_FSA", valor: 0.01 }, // aporte previsional provincial — específico de Formosa, ajustar por empresa si aplica
    // Montos fijos (no %) — EMPLEADOR!G9:L9 de GONZALEZ.xlsm
    { clave: "ART_FFEP_FIJO", valor: 615 },
    { clave: "SVO_FIJO", valor: 175.89 },
    { clave: "APORTE_SOLIDARIO_OSECAC_FIJO", valor: 100 },
    { clave: "DETRACCION_ART22_CON_SAC", valor: 7003.68 },
    { clave: "DETRACCION_ART22_SIN_SAC", valor: 3618.568 },
    { clave: "DETRACCION_ART23_CONTRIBUCIONES", valor: 1800 },
    // Antigüedad/presentismo (motor de liquidación mensual) — 1%/año es el estándar LCT/CCT más
    // común, cualquier empresa/categoría puede sobreescribirlo si su convenio difiere.
    { clave: "ANTIGUEDAD_PORCENTAJE_ANIO", valor: 0.01 },
    // RIFL (Título XX Ley 27.802): 0 por defecto — no reglamentado todavía, no inventar el %.
    { clave: "RIFL_REDUCCION_CONTRIBUCIONES", valor: 0 },
    // FAL y topes de deducción (Ley 27.802)
    { clave: "FAL_GRANDE", valor: 0.01 },
    { clave: "FAL_PYME", valor: 0.025 },
    { clave: "TOPE_DEDUCCION_GENERAL", valor: 0.2 },
    { clave: "TOPE_DEDUCCION_SINDICAL", valor: 0.02 },
  ];

  for (const t of tasasGlobales) {
    const existente = await db.tasaLaboral.findFirst({
      where: { empresaId: null, clave: t.clave, vigenciaHasta: null },
    });
    if (!existente) {
      await db.tasaLaboral.create({
        data: { clave: t.clave, valor: t.valor, vigenciaDesde },
      });
    }
  }

  console.log("Sembrando catálogo global de conceptos...");
  const conceptosGlobales: Array<Parameters<typeof db.conceptoDefinicion.create>[0]["data"]> = [
    { codigo: "BASICO", nombre: "Sueldo básico", tipo: "REMUNERATIVO", afectaAportes: true, afectaContribuciones: true, afectaSAC: true, ordenImpresion: 1 },
    { codigo: "SAC", nombre: "SAC (aguinaldo)", tipo: "REMUNERATIVO", afectaAportes: true, afectaContribuciones: true, afectaSAC: false, ordenImpresion: 2 },
    { codigo: "APORTES", nombre: "Aportes (jubilación + ley 19.032 + obra social)", tipo: "DEDUCCION", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 90 },
    { codigo: "SAC_NR", nombre: "SAC sobre no remunerativos", tipo: "NO_REMUNERATIVO", afectaAportes: false, afectaContribuciones: true, afectaSAC: false, ordenImpresion: 3 },
    // Contribuciones patronales individuales — Sección B del recibo Anexo III (Dec. 407/2026):
    // el costo laboral total se expone por rubro, ANTES del bruto. Antes de esto el motor solo
    // calculaba un monto agregado (`LiquidacionMensual.totalContribucionesPatronales`); estos
    // conceptos permiten desglosarlo.
    { codigo: "CP_JUBILACION", nombre: "Contribución jubilación (patronal)", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "SEGURIDAD_SOCIAL", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 100 },
    { codigo: "CP_LEY19032", nombre: "Contribución Ley 19.032 (patronal)", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "INSSJP_PAMI", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 101 },
    { codigo: "CP_OBRA_SOCIAL", nombre: "Contribución obra social (patronal)", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "OBRA_SOCIAL", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 102 },
    { codigo: "CP_ASIG_FAMILIARES", nombre: "Contribución asignaciones familiares", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "SEGURIDAD_SOCIAL", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 103 },
    { codigo: "CP_FNE", nombre: "Contribución Fondo Nacional de Empleo", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "SEGURIDAD_SOCIAL", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 104 },
    { codigo: "CP_ART", nombre: "ART (alícuota + cuota fija FFEP)", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "ART", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 105 },
    { codigo: "CP_SVO", nombre: "Seguro colectivo de vida obligatorio (SVO)", tipo: "CONTRIBUCION_PATRONAL", rubroRecibo: "OTROS_CONVENCIONALES", afectaAportes: false, afectaContribuciones: false, afectaSAC: false, ordenImpresion: 106 },
    {
      codigo: "TICKET_COMIDA",
      nombre: "Ticket / vales de comida",
      tipo: "NO_REMUNERATIVO",
      subtipo: "BENEFICIO_SOCIAL_103BIS",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      ordenImpresion: 10,
    },
    {
      codigo: "REEMBOLSO_MEDICO",
      nombre: "Reembolso gastos médicos/farmacia",
      tipo: "NO_REMUNERATIVO",
      subtipo: "BENEFICIO_SOCIAL_103BIS",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      ordenImpresion: 11,
    },
    {
      codigo: "VIATICOS",
      nombre: "Viáticos",
      tipo: "NO_REMUNERATIVO",
      subtipo: "NO_REMUN_105",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      ordenImpresion: 12,
    },
    {
      codigo: "BONO_VARIABLE",
      nombre: "Bono variable por objetivos",
      tipo: "REMUNERATIVO",
      subtipo: "DINAMICO_104BIS",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      esVariable: true,
      ordenImpresion: 20,
    },
    {
      codigo: "SINDICAL",
      nombre: "Cuota sindical",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      ordenImpresion: 91,
    },
    {
      codigo: "EMBARGO",
      nombre: "Embargo judicial",
      tipo: "DEDUCCION",
      subtipo: "EMBARGO",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      ordenImpresion: 92,
    },
    {
      codigo: "PRESTAMO",
      nombre: "Préstamo / adelanto",
      tipo: "DEDUCCION",
      subtipo: "OTRA_DEDUCCION",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      requiereConsentimiento: true,
      ordenImpresion: 93,
    },
  ];

  for (const c of conceptosGlobales) {
    const existente = await db.conceptoDefinicion.findFirst({
      where: { empresaId: null, codigo: c.codigo },
    });
    if (!existente) {
      await db.conceptoDefinicion.create({ data: c });
    }
  }

  console.log("Sembrando catálogo real Comercio CCT 130/75 (GONZALEZ.xlsm, hoja CONCEPTOS)...");
  const conceptosComercio130_75: Array<Parameters<typeof db.conceptoDefinicion.create>[0]["data"]> = [
    {
      codigo: "10001",
      codigoArca: "110000",
      nombre: "SUELDO BASICO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      activo: false, // duplicaría la línea sintética BASICO/SAC/APORTES del motor actual
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10002",
      codigoArca: "160001",
      nombre: "ANTIGÜEDAD",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10003",
      codigoArca: "170001",
      nombre: "PRESENTISMO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10004",
      codigoArca: "110000",
      nombre: "INASISTENCIAS",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10005",
      codigoArca: "110007",
      nombre: "PLUS FERIADO NO TRABAJADO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10006",
      codigoArca: "110000",
      nombre: "DIA EMPLEADO DE COMERCIO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10007",
      codigoArca: "110000",
      nombre: "LIC. POR ENFERMEDAD",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10008",
      codigoArca: "110000",
      nombre: "INASISTENCIAS JUSTIFICADAS",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10009",
      codigoArca: "110007",
      nombre: "FERIADO TRABAJADO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10010",
      codigoArca: "120000",
      nombre: "S.A.C.",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10011",
      codigoArca: "120001",
      nombre: "S.A.C. 1° SEMESTRE",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10012",
      codigoArca: "120002",
      nombre: "S.A.C. 2° SEMESTRE",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10013",
      codigoArca: "120003",
      nombre: "S.A.C. PROPORCIONAL",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10014",
      codigoArca: "150000",
      nombre: "VACACIONES",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10015",
      codigoArca: "130001",
      nombre: "HS. EXTRA 50%",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      esVariable: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10016",
      codigoArca: "130002",
      nombre: "HS. EXTRA 100%",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      esVariable: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "10017",
      codigoArca: "110001",
      nombre: "PREAVISO",
      tipo: "REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: true,
      aportesSipa: true,
      contribSipa: true,
      aportesInssjp: true,
      contribInssjp: true,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: true,
      contribRenatea: true,
      contribAsigFamiliares: true,
      contribFNE: true,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20001",
      codigoArca: "551000",
      nombre: "ADICIONAL NO REMUNERATIVO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20002",
      codigoArca: "550000",
      nombre: "ANTIGÜEDAD NO REMUNERATIVO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20003",
      codigoArca: "550000",
      nombre: "PRESENTISMO NO REMUNERATIVO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20004",
      codigoArca: "520012",
      nombre: "VACACIONES NO GOZADAS",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20005",
      codigoArca: "520014",
      nombre: "INDEMNIZACION POR DESPIDO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20006",
      codigoArca: "520016",
      nombre: "INTEGRACION MES DE DESPIDO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20007",
      codigoArca: "520018",
      nombre: "S.A.C. SOBRE VACACIONES NO GOZADAS",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20008",
      codigoArca: "551000",
      nombre: "INASISTENCIAS NO REM.",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20009",
      codigoArca: "551000",
      nombre: "INASISTENCIAS JUSTIFICADAS NO REM.",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20010",
      codigoArca: "551000",
      nombre: "LIC. POR ENFERMEDAD NO REM",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: true,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: true,
      contribObraSocial: true,
      aportesFondoSolidario: true,
      contribFondoSolidario: true,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "20011",
      codigoArca: "520015",
      nombre: "SUSTITUTIVO PREAVISO",
      tipo: "NO_REMUNERATIVO",
      afectaAportes: false,
      afectaContribuciones: true,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: true,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30001",
      codigoArca: "810000",
      nombre: "JUBILACION",
      tipo: "DEDUCCION",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      activo: false, // duplicaría la línea sintética BASICO/SAC/APORTES del motor actual
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30002",
      codigoArca: "810001",
      nombre: "LEY Nº 19.032 (INSSJP)",
      tipo: "DEDUCCION",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      activo: false, // duplicaría la línea sintética BASICO/SAC/APORTES del motor actual
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30003",
      codigoArca: "810002",
      nombre: "OBRA SOCIAL",
      tipo: "DEDUCCION",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      activo: false, // duplicaría la línea sintética BASICO/SAC/APORTES del motor actual
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30004",
      codigoArca: "810004",
      nombre: "SINDICATO",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      rubroRecibo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30005",
      codigoArca: "810004",
      nombre: "FAECYS",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      rubroRecibo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30006",
      codigoArca: "810002",
      nombre: "APORTE SOLIDARIO OSECAC",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      rubroRecibo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30007",
      codigoArca: "810002",
      nombre: "OBRA SOCIAL NO REM.",
      tipo: "DEDUCCION",
      rubroRecibo: "OBRA_SOCIAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30008",
      codigoArca: "810004",
      nombre: "SINDICATO NO REM",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      rubroRecibo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30009",
      codigoArca: "810004",
      nombre: "FAECYS NO REM",
      tipo: "DEDUCCION",
      subtipo: "SINDICAL",
      rubroRecibo: "SINDICAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
    {
      codigo: "30010",
      codigoArca: "820000",
      nombre: "IPS FSA",
      tipo: "DEDUCCION",
      rubroRecibo: "SEGURIDAD_SOCIAL",
      afectaAportes: false,
      afectaContribuciones: false,
      afectaSAC: false,
      aportesSipa: false,
      contribSipa: false,
      aportesInssjp: false,
      contribInssjp: false,
      aportesObraSocial: false,
      contribObraSocial: false,
      aportesFondoSolidario: false,
      contribFondoSolidario: false,
      aportesRenatea: false,
      contribRenatea: false,
      contribAsigFamiliares: false,
      contribFNE: false,
      contribLRT: false,
      afectaRegDiferenciales: false,
      afectaRegEspeciales: false,
    },
  ];

  for (const c of conceptosComercio130_75) {
    const existente = await db.conceptoDefinicion.findFirst({
      where: { empresaId: null, codigo: c.codigo },
    });
    if (!existente) {
      await db.conceptoDefinicion.create({ data: c });
    }
  }

  console.log("Creando usuario contador...");
  const contadorPassword = await bcrypt.hash("contador123", 12);
  const contador = await db.usuario.upsert({
    where: { email: "contador@estudio.com" },
    update: {},
    create: {
      email: "contador@estudio.com",
      nombre: "Contador Demo",
      passwordHash: contadorPassword,
      role: "CONTADOR",
    },
  });

  console.log("Creando empresas de ejemplo...");
  const empresaA = await db.empresa.upsert({
    where: { cuit: "30-71234567-8" },
    update: {},
    create: {
      razonSocial: "Comercial del Sur S.A.",
      cuit: "30-71234567-8",
      actividad: "Comercio minorista",
      tamano: "PEQUENA",
      provincia: "Buenos Aires",
    },
  });

  const empresaB = await db.empresa.upsert({
    where: { cuit: "30-70987654-3" },
    update: {},
    create: {
      razonSocial: "Constructora Andina S.R.L.",
      cuit: "30-70987654-3",
      actividad: "Construcción",
      tamano: "MEDIANA",
      provincia: "Mendoza",
    },
  });

  console.log("Creando categorías de convenio (escala real CCT 130/75, ESCALA SALARIAL de GONZALEZ.xlsm)...");
  const catAdmin = await db.categoriaConvenio.upsert({
    where: { empresaId_nombre_vigenciaDesde: { empresaId: empresaA.id, nombre: "Administrativo A", vigenciaDesde } },
    update: {},
    create: {
      empresaId: empresaA.id,
      nombre: "Administrativo A",
      convenioNombre: "CCT 130/75",
      salarioBaseConvenio: 445901.43,
      remuneracionNoRemunerativa: 259692.97,
      vigenciaDesde,
    },
  });

  // "Vendedor B": mismos valores que el caso de regresión de GONZALEZ IVAN (legajo 3, JUN/2024).
  const catVendedor = await db.categoriaConvenio.upsert({
    where: { empresaId_nombre_vigenciaDesde: { empresaId: empresaA.id, nombre: "Vendedor B", vigenciaDesde } },
    update: {},
    create: {
      empresaId: empresaA.id,
      nombre: "Vendedor B",
      convenioNombre: "CCT 130/75",
      salarioBaseConvenio: 457088.37,
      remuneracionNoRemunerativa: 302373,
      vigenciaDesde,
    },
  });

  const catOficial = await db.categoriaConvenio.upsert({
    where: { empresaId_nombre_vigenciaDesde: { empresaId: empresaB.id, nombre: "Oficial", vigenciaDesde } },
    update: {},
    create: {
      empresaId: empresaB.id,
      nombre: "Oficial",
      convenioNombre: "CCT 76/75 UOCRA",
      salarioBaseConvenio: 900000,
      vigenciaDesde,
    },
  });

  console.log("Creando legajos de ejemplo...");
  const legajosSeed = [
    {
      empresaId: empresaA.id,
      numeroLegajo: 1,
      nombre: "Ana",
      apellido: "García",
      cuil: "27-30123456-4",
      fechaNacimiento: new Date("1988-04-12"),
      fechaIngreso: new Date("2019-03-01"),
      categoriaId: catAdmin.id,
      tipoContrato: "TIEMPO_INDETERMINADO" as const,
      modalidadRemuneracion: "MENSUAL" as const,
      sueldoBasico: 950000,
    },
    {
      empresaId: empresaA.id,
      numeroLegajo: 2,
      nombre: "Martín",
      apellido: "Pérez",
      cuil: "20-32456789-1",
      fechaNacimiento: new Date("1992-09-23"),
      fechaIngreso: new Date("2022-06-15"),
      categoriaId: catVendedor.id,
      tipoContrato: "TIEMPO_INDETERMINADO" as const,
      modalidadRemuneracion: "MENSUAL" as const,
      sueldoBasico: 820000,
    },
    {
      empresaId: empresaA.id,
      numeroLegajo: 3,
      nombre: "Lucía",
      apellido: "Fernández",
      cuil: "27-35678912-0",
      fechaNacimiento: new Date("1995-01-30"),
      fechaIngreso: new Date("2024-02-01"),
      categoriaId: catVendedor.id,
      tipoContrato: "PART_TIME" as const,
      modalidadRemuneracion: "MENSUAL" as const,
      sueldoBasico: 780000,
      horasSemanales: 20,
      horasSemanalesFullTime: 40,
    },
    {
      empresaId: empresaB.id,
      numeroLegajo: 1,
      nombre: "Jorge",
      apellido: "Álvarez",
      cuil: "20-28123456-2",
      fechaNacimiento: new Date("1980-11-05"),
      fechaIngreso: new Date("2012-08-20"),
      categoriaId: catOficial.id,
      tipoContrato: "TIEMPO_INDETERMINADO" as const,
      modalidadRemuneracion: "MENSUAL" as const,
      sueldoBasico: 1050000,
    },
    {
      empresaId: empresaB.id,
      numeroLegajo: 2,
      nombre: "Verónica",
      apellido: "Torres",
      cuil: "27-33123456-7",
      fechaNacimiento: new Date("1990-06-18"),
      fechaIngreso: new Date("2021-01-10"),
      categoriaId: catOficial.id,
      tipoContrato: "TIEMPO_INDETERMINADO" as const,
      modalidadRemuneracion: "MENSUAL" as const,
      sueldoBasico: 990000,
    },
  ];

  for (const legajo of legajosSeed) {
    await db.legajo.upsert({
      where: { cuil: legajo.cuil },
      update: {},
      create: legajo,
    });
  }

  console.log("Creando usuario cliente de ejemplo...");
  const clientePassword = await bcrypt.hash("cliente123", 12);
  await db.usuario.upsert({
    where: { email: "cliente@comercialdelsur.com" },
    update: {},
    create: {
      email: "cliente@comercialdelsur.com",
      nombre: "Cliente Comercial del Sur",
      passwordHash: clientePassword,
      role: "CLIENTE",
      empresaId: empresaA.id,
    },
  });

  console.log("Listo. Usuarios de prueba:");
  console.log("  contador@estudio.com / contador123 (CONTADOR)");
  console.log("  cliente@comercialdelsur.com / cliente123 (CLIENTE)");
  console.log(`Usuario contador id: ${contador.id}`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
