-- AlterEnum
ALTER TYPE "ClaveTasa" ADD VALUE 'ANTIGUEDAD_MONTO_FIJO_ANIO_UECARA';
ALTER TYPE "ClaveTasa" ADD VALUE 'PRESENTISMO_PORCENTAJE_UECARA';
ALTER TYPE "ClaveTasa" ADD VALUE 'CUOTA_SINDICAL_UECARA';
